config/routes.rb
Rails.application.routes.draw do
 
  root "sessions#new"
  post 'sessions/login'
  get 'dashboard/' => 'dashboard#index'
  get 'sessions/authendicate'
  get 'sessions/logout'
  resources :users_roles
  resources :events, only: [:new, :edit, :destroy, :update, :create]
  resources :roles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate
  def index
    @user = @current_user
    @events = Event.paginate(:page => params[:page])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= @user.firstname %>  <%= @user.lastname %>
          </div>
          <div class="profile-usertitle-name">
            <%= @user.role.name %>  
          </div>
        </div>
        <div class="profile-usermenu">
          <ul class="nav">
            <li class="active">
              <a href="#">Profile</a>
            </li>
            <li>
              <a href="#">
                <i class="glyphicon glyphicon-user"></i>
                Email: <%= @user.email %> 
              </a>
            </li>
            <li>
              <a href="#" target="_blank">
                <i class="glyphicon glyphicon-ok"></i>
                Gender: <%= @user.gender %> 
              </a>
            </li>
            <li>
              <a href="#">
                <i class="glyphicon glyphicon-flag"></i>
                DOB: <%= @user.dob.to_date %> 
              </a>
            </li>
            <li>
              <a href="#">
                <i class="glyphicon glyphicon-flag"></i>
                Phone<%= @user.phone %> 
              </a>
            </li>
            <li>
              <%= link_to 'Logout', sessions_logout_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">

        <h3>Events</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Description</th>
              <th>Start date</th>
              <th>End date</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
            <tr>
              <td><%= event.id %></td>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.start_date.to_date %></td>
              <td><%= event.end_date.to_date %></td>
              <% if @user.role.name=="Manager" %>
              <td>
                <%= link_to 'Edit', edit_event_path(event) %>
              </td>
              <td>
                <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
              <% end %>
            </tr>
            <% end %>

          </tbody>
        </table>
        <%= will_paginate @events, class: "pagination" %>
        <br>
        <% if @user.role.name=="Manager" %>
          <%= link_to 'New Event', new_event_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>