config/routes.rb
Rails.application.routes.draw do
 
  root "sessions#new"
  post 'sessions/login'
  get 'dashboard/' => 'dashboard#index'
  get 'sessions/authendicate'
  get 'sessions/logout'
  resources :users_roles
  resources :events, only: [:new, :edit, :destroy, :update, :create]
  resources :roles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
   self.per_page = 10
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.save
    redirect_to dashboard_path
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.update(event_params)
    redirect_to dashboard_path
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    redirect_to dashboard_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_list.html.erb
      <h3>Events</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Start date</th>
            <th>End date</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= event.name %></td>
            <td><%= event.description %></td>
            <td><%= event.start_date.to_date %></td>
            <td><%= event.end_date.to_date %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
      <%= will_paginate @events, class: "pagination" %>
      <br>
    

app/views/events/_form.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">Event Form</div>
    <div class="panel-body">
      <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :event_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :event_description , class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :start_date %>
        <%= form.datetime_select :start_date, id: :event_start_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :end_date %>
        <%= form.datetime_select :end_date, id: :event_end_date, class: 'form-control' %>
      </div>

      <div class="actions">
        <button class="btn btn-info">Submit</button>
      </div>
      <% end %></div>
    </div>

app/views/events/edit.html.erb
<div class="container">
<h3>Editing Event</h3>

<%= render 'form', event: @event %>

<%= link_to 'Home', dashboard_path %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Event List</div>
    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <h1>Events</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Start date</th>
            <th>End date</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.description %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= link_to 'Show', event %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New Event', new_event_path %>
      <%= link_to 'Home', dashboard_path %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <h3>Create Event</h3>
  <%= render 'form', event: @event %>

  <%= link_to 'Home', dashboard_path %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>